import { Link } from 'react-router-dom'
import { useAuth } from '../hooks/useAuth'
import { FileText, Shield, AlertTriangle, Users, Plus } from 'lucide-react'

export default function DashboardPage() {
  const { user, role } = useAuth()

  const name = user?.email?.split('@')[0] || 'Advisor'

  return (
    <div>
      <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', marginBottom: '2rem' }}>
        <div>
          <div className="page-title">GJM Ultra Brokers</div>
          <p className="page-sub">Compliance Management Portal — Welcome back, {name}</p>
        </div>
        <Link to="/session" className="btn btn-gold btn-lg">
          <Plus size={18} /> New Client Session
        </Link>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: '1.5rem', marginBottom: '2rem' }}>
        {[
          { icon: <FileText size={24} />, label: 'Client Session', desc: 'Generate FICA compliance documents for a client', link: '/session', color: 'var(--navy)' },
          { icon: <Shield size={24} />, label: 'POPIA Notice', desc: 'No client data is stored. Documents generated in-browser only.', color: 'var(--success)', link: null },
          { icon: <AlertTriangle size={24} />, label: 'FICA Compliance', desc: 'Always refer TFS/PEP/PIP=YES cases to Tanya Van Niekerk immediately.', color: 'var(--warn)', link: null },
        ].map((item, i) => (
          <div key={i} className="card">
            <div className="card-body" style={{ display: 'flex', gap: '1rem', alignItems: 'flex-start' }}>
              <div style={{ color: item.color, flexShrink: 0, marginTop: '0.1rem' }}>{item.icon}</div>
              <div>
                <div style={{ fontWeight: 700, marginBottom: '0.25rem', color: 'var(--navy)' }}>{item.label}</div>
                <div className="text-muted text-sm">{item.desc}</div>
                {item.link && <Link to={item.link} className="btn btn-primary btn-sm" style={{ marginTop: '0.75rem' }}>Open →</Link>}
              </div>
            </div>
          </div>
        ))}
      </div>

      <div className="card">
        <div className="card-header">
          <Users size={18} color="var(--gold)" />
          <h2>Documents Available</h2>
        </div>
        <div className="card-body">
          <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '0.88rem' }}>
            <thead>
              <tr style={{ borderBottom: '2px solid var(--border)' }}>
                <th style={{ textAlign: 'left', padding: '0.6rem', color: 'var(--slate)', fontWeight: 600 }}>Document</th>
                <th style={{ textAlign: 'left', padding: '0.6rem', color: 'var(--slate)', fontWeight: 600 }}>When to Use</th>
                <th style={{ textAlign: 'left', padding: '0.6rem', color: 'var(--slate)', fontWeight: 600 }}>Regulation</th>
              </tr>
            </thead>
            <tbody>
              {[
                ['Onboarding Questionnaire', 'All new clients and clients not seen in 36+ months', 'FICA — Client Due Diligence'],
                ['Ongoing Due Diligence', 'Existing clients — periodic review', 'FICA — Ongoing Monitoring'],
                ['Transactional DD', 'Each new transaction / policy change', 'FICA — Transactional Monitoring'],
                ['RA Calculation', 'Retirement annuity proposals', 'FAIS — Suitability / Best Interest'],
                ['FNA Calculator', 'Full financial needs analysis', 'FAIS — Section 8 Record of Advice'],
                ['Risk ROA', 'Risk Client Advice Record with AI product comparison', 'FAIS — Section 9 Record of Advice'],
              ].map(([doc, when, reg], i) => (
                <tr key={i} style={{ borderBottom: '1px solid var(--border)' }}>
                  <td style={{ padding: '0.6rem', fontWeight: 600, color: 'var(--navy)' }}>{doc}</td>
                  <td style={{ padding: '0.6rem', color: 'var(--slate)' }}>{when}</td>
                  <td style={{ padding: '0.6rem' }}><span style={{ fontSize: '0.75rem', background: 'var(--bg)', border: '1px solid var(--border)', padding: '0.15em 0.6em', borderRadius: '20px' }}>{reg}</span></td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {role === 'compliance_officer' && (
        <div className="alert alert-info" style={{ marginTop: '1.5rem' }}>
          <Shield size={15} />
          <span><strong>Compliance Officer View:</strong> You are logged in as a Compliance Officer. All high-risk client documents generated by advisors require your physical sign-off before filing.</span>
        </div>
      )}
    </div>
  )
}
